

function About() {
    return (
      <>
      <div className="flex justify-center" style={{ paddingTop: '20px' }}>
        <h1 className="p-5 text-5xl bg-blue-400">How It Works</h1>
      </div>
      <div style={{ paddingTop: '20px', paddingBottom: '30px'}}>
      <div style={{ display: 'flex', alignItems: 'center' }}>
      <div style={{ flex: 1, marginLeft: '20px', marginRight: '30px' }}>
        <p className="large-text">
        1. Analyzing Comments
        Our platform employs cutting-edge machine learning algorithms, including the Perspective API, to analyze the toxicity of comments in real-time. The Perspective API provides a toxicity score ranging from 0 to 1, indicating the likelihood that a comment could be perceived as toxic. A score closer to 0 indicates low toxicity and a score closer to 1 indicates higher toxicity.<br />
        2. Providing Insights
        Based on the toxicity score generated by the Perspective API, we provide insightful feedback on the potential toxicity of comments. Users can easily interpret the toxicity level of their comments and make informed decisions about their online interactions. <br />
        3. Promoting Healthy Discussions
        By leveraging the insights provided by the Perspective API, we aim to promote healthier and more constructive online discussions. Our platform empowers users to identify and address toxic behavior, fostering a safer and more respectful digital environment for all.

        </p>
      </div>
      <div style={{ flex: 1 }}>
        <img src="/step2.jpg" alt="About Image" style={{ maxWidth: '100%', borderRadius: '10px', width:'600px', height: '500px',}} />
      </div>
      </div>
      </div>
      <footer className="bg-blue-400 text-white py-8">
        {/* Footer content */}
        <div className="container mx-auto flex justify-around items-center h-full">
          <div>
            <h3 className="p-5 text-3xl">Contact Us</h3>
            <p>Email: info@comment-analyzer.com</p>
            <p>Address: 123 Flower Street, Charlotte NC, US</p>
            <p>Phone: 123-456-7890</p>
          </div>
          <div>
            <h3 className="p-5 text-3xl">Useful Links</h3>
            <p>About</p>
            <p>Dashboard</p>
            <p>Sign Up</p>
          </div>
          <div>
            <h3 className="p-5 text-3xl">Learn More</h3>
            <p>Machine Learning</p>
            <p>Perspective API</p>
            <p>Natural Language Processing</p>
          </div>
        </div>
        <div className="text-center" style={{ paddingTop: '40px' }}>
          <p>&copy; 2024 Comment Analyzer</p>
        </div>
      </footer>
      </>
    )
  }
  
  export default About